# Generated by Django 3.1.5 on 2021-03-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_file_image_resource_text_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.CharField(choices=[('U', 'Undergraduate'), ('PG', 'Postraduate'), ('P', 'PhD'), ('PT', 'Part-Time')], default='U', max_length=2),
        ),
    ]
