# Generated by Django 3.1.5 on 2021-03-23 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0003_auto_20210323_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='modules_enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
